name: "pretendo-dev-core"

services:
  mongo:
    image: mongo:8.0
    restart: unless-stopped
    networks:
      - "pretendo"
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - "mongo_data:/data/db"
      - "mongo_config:/data/configdb"

  pg:
    image: postgres:17
    restart: unless-stopped
    networks:
      - "pretendo"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  minio:
    image: minio/minio
    restart: unless-stopped
    networks:
      - "pretendo"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DOMAIN: minio
    command: server /data --console-address ":9001"
    volumes:
      - "minio_data:/data"
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      retries: 3
      timeout: 5s
  minio-setup:
    image: minio/mc
    networks:
      - "pretendo"
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DOMAIN: minio
    volumes:
      - "./create-buckets.sh:/etc/minio/create-buckets.sh"
    entrypoint: "/etc/minio/create-buckets.sh"

  account:
    image: ghcr.io/pretendonetwork/account:edge
    restart: unless-stopped
    networks:
      - "pretendo"
    ports:
      - "8200:8200"
      - "8123:8123"
    environment:
      PN_ACT_CONFIG_REDIS_URL: redis://redis:6379
      PN_ACT_CONFIG_HTTP_PORT: 8200
      PN_ACT_CONFIG_GRPC_PORT: 8123
      PN_ACT_CONFIG_MONGO_CONNECTION_STRING: "mongodb://mongo:27017/account?directConnection=true"
      PN_ACT_CONFIG_S3_ENDPOINT: "http://minio:9000"
      PN_ACT_CONFIG_S3_REGION: "us-east-1"
      PN_ACT_CONFIG_S3_BUCKET: "miiverse"
      PN_ACT_CONFIG_S3_ACCESS_KEY: "minioadmin"
      PN_ACT_CONFIG_S3_ACCESS_SECRET: "minioadmin"
      PN_ACT_CONFIG_CDN_BASE_URL: "http://cdn.pretendo.cc/miiverse"
      PN_ACT_CONFIG_AES_KEY: "1234567812345678123456781234567812345678123456781234567812345678"
      PN_ACT_CONFIG_GRPC_MASTER_API_KEY_ACCOUNT: "12345678123456781234567812345678"
      PN_ACT_CONFIG_GRPC_MASTER_API_KEY_API: "12345678123456781234567812345678"

  friends:
    image: ghcr.io/pretendonetwork/friends:edge
    restart: unless-stopped
    networks:
      - "pretendo"
    ports:
      - "8124:8124"
    environment:
      PN_FRIENDS_CONFIG_DATABASE_URI: "postgres://postgres:postgres@localhost:5432/friends"
      PN_FRIENDS_CONFIG_AES_KEY: "1234567812345678123456781234567812345678123456781234567812345678"
      PN_FRIENDS_CONFIG_GRPC_API_KEY: "12345678123456781234567812345678"
      PN_FRIENDS_GRPC_SERVER_PORT: 8124
      PN_FRIENDS_AUTHENTICATION_SERVER_PORT: 60000
      PN_FRIENDS_SECURE_SERVER_HOST: "friends"
      PN_FRIENDS_SECURE_SERVER_PORT: 60001
      PN_FRIENDS_ACCOUNT_GRPC_HOST: "account"
      PN_FRIENDS_ACCOUNT_GRPC_PORT: 8123
      PN_FRIENDS_ACCOUNT_GRPC_API_KEY: "12345678123456781234567812345678"

  proxy:
    image: mitmproxy/mitmproxy:latest
    network_mode: host
    command: > 
      mitmweb -v --mode regular@8888
      --certs *=/data/mitm-ca.pem
      -s /data/mitmproxy.py
      --web-host 0.0.0.0 --set web_password=proxyadmin
      -k --set tls_version_client_min=UNBOUNDED --set tls_version_server_min=UNBOUNDED 
      --set key_size=1024
    volumes:
      - "./mitmproxy.py:/data/mitmproxy.py:ro"
      - "../../assets/certs/mitm-ca.pem:/data/mitm-ca.pem:ro"
      - "./.mitmproxy/:/home/mitmproxy/.mitmproxy/"

volumes:
  mongo_data:
  pg_data:
  mongo_config:
  minio_data:

networks:
  pretendo:
    driver: bridge
